php-version = "8.4"

[source]
paths = ["app", "tests"]
includes = ["vendor"]
excludes = [
  "./.tempest",
  "./vendor/symfony/cache/Traits/ValueWrapper.php",
  "./vendor/composer",
]

[analyzer]
# Enable all checks
find-unused-expressions = true
find-unused-definitions = true
analyze-dead-code = true
check-throws = true
check-missing-override = true
find-unused-parameters = true
check-missing-type-hints = true
check-closure-missing-type-hints = true
check-arrow-function-missing-type-hints = true

[formatter]
print-width = 80

[linter]
integrations = ["tempest"]

[linter.rules]
